#!/usr/bin/python
#
# Test program to verify that NIS functions properly.
#
# Currently, this tests:
#
#  - different binding modes configured via yp.conf
#  - ypcat, ypmatch
#  - nss integration of hosts, passwd, group
#  - PAM integration (authentication, passwd change)
#
# Things not covered yet
#  - IPv6
#  - master/slave setups
#  - SLP binding
#  - ypbind fallback to broadcast if a configured
#    server cannot be found
#  - unbinding when the server goes away
#  - ypset
#
# Copyright (C) 2015 Olaf Kirch <okir@suse.de>
#

import sys
import suselog
import twopence
import susetest
import time


journal = None
client = None
server = None
rpcinfo = None
nisdomain = "twopence-nistest"
nismaster = "nismaster"
nisclient = "nisclient"

def setup():
	global client, server, journal

	config = susetest.Config("nis")

	journal = config.journal

	journal.beginGroup("setup")

	client = config.target("client")
	server = config.target("server")

	if not client.ipaddr:
		journal.fatal("No IP address set for client");
	if not server.ipaddr:
		journal.fatal("No IP address set for server");

	if server.ipv6_addr:
		journal.info("IPv6 tests enabled")
	else:
		journal.info("IPv6 tests disabled")

	if not server.configureOtherNetworks():
		journal.fatal("Unable to configure additional networks")
	if not client.configureOtherNetworks():
		journal.fatal("Unable to configure additional networks")

	journal.finishGroup()

##################################################################
# Start NIS master server and run some sanity checks
##################################################################
def nis_init_master_server(server):
	global journal

	journal.beginGroup("init-%s" % server.name, "initialize server")

	journal.beginTest("Preparing configuration")

	journal.info("set the NIS domain to %s" % nisdomain)
	if not server.runOrFail("nisdomainname '%s'" % nisdomain):
		return False

	journal.info("Set the host name to nismaster")
	server.addHostEntry(server.ipaddr, nismaster)
	if (server.ipv6_addr):
		server.addHostEntry(server.ipv6_addr, nismaster)
	server.run("hostname > /etc/hostname.tpsave")
	server.run("hostname %s" % nismaster)

	journal.beginTest("start rpcbind")
	if not server.runOrFail("systemctl enable rpcbind.socket") or \
	   not server.runOrFail("systemctl start rpcbind.socket"):
		return False

	journal.beginTest("starting ypserv")
	if not server.runOrFail("rcypserv start"):
		return False

	journal.beginTest("starting yppasswdd")
	if not server.runOrFail("rcyppasswdd start"):
		return False

	journal.beginTest("ensure ypserv is running")
	if not server.runOrFail("rpcinfo -u localhost ypserv"):
		return False

	journal.beginTest("ensure yppasswdd is running")
	if not server.runOrFail("rpcinfo -u localhost yppasswdd"):
		return False

	# Build maps after server was started to avoid lot of error
	# messages in output
	journal.beginTest("building default NIS maps")
	if not server.runOrFail("make -C /var/yp"):
		return False

	journal.finishGroup()

##################################################################
# Stop NIS master server
##################################################################
def nis_stop_master_server(server):
	global journal

	journal.beginGroup("stop-%s" % server.name, "stop master server")

	journal.beginTest("stoping yppasswdd")
	if not server.runOrFail("rcyppasswdd stop"):
		return False

	journal.beginTest("Removing default NIS maps")
	if not server.runOrFail("rm -rf  /var/yp/" + nisdomain):
		return False

	journal.beginTest("stoping ypserv")
	if not server.runOrFail("rcypserv stop"):
		return False

	journal.beginTest("stop", "disable rpcbind on server")
	server.runOrFail("/usr/bin/systemctl disable rpcbind.socket")
	server.runOrFail("/usr/bin/systemctl stop rpcbind.socket")

	server.run("hostname `cat /etc/hostname.tpsave`")
	server.run("rm -f /etc/hostname.tpsave")

	journal.finishGroup()


##################################################################
# Start slave ypserv and run some sanity checks
##################################################################
def nis_init_slave_server(slave):
	global journal

	journal.beginGroup("init-slave-%s" % slave.name, "initialize NIS slave server")

	journal.beginTest("Preparing configuration")

	#journal.info("set the NIS domain to %s" % nisdomain)
	#if not server.runOrFail("nisdomainname '%s'" % nisdomain):
	#        return False

	# Remove old stuff
	journal.beginTest("Removing old NIS maps")
	if not slave.runOrFail("rm -rf  /var/yp/" + nisdomain):
		return False

	journal.beginTest("starting ypserv")
	if not slave.runOrFail("rcypserv start"):
		return False

	journal.beginTest("ensure ypserv is running")
	if not slave.runOrFail("rpcinfo -u localhost ypserv"):
		return False

	# Fetch initial maps from master server
	journal.beginTest("fetch default maps")
	if not slave.runOrFail("/usr/lib/yp/ypinit -s %s" % nismaster):
		return False

	nis_verify_maps_exist(slave)

	journal.finishGroup()

def nis_verify_maps_exist(slave):

	global journal;

	journal.beginTest("Make sure yphelper -m [nismaster] shows output")
	st = client.runOrFail("/usr/lib/yp/yphelper -m %s" % nismaster, quiet = True)
	if not st:
		return False

	if not st.stdout:
		journal.failure("yphelper returned an empty list")
		return False

	journal.success("yphelper returned map list (%u lines)" % len(str(st.stdout).split('\n')))
	return True


##################################################################
# Stop ypserv on slave
##################################################################
def nis_stop_slave_server(slave):
	global journal

	journal.beginGroup("stop-slave-%s" % slave.name, "stop slave server")

	journal.beginTest("Removing slave NIS maps")
	if not server.runOrFail("rm -rf  /var/yp/" + nisdomain):
		return False

	journal.beginTest("stoping ypserv")
	if not server.runOrFail("rcypserv stop"):
		return False

	journal.finishGroup()

##################################################################
# Start ypbind and run some sanity checks
##################################################################
def nis_init_client(client, server):
	global journal

	journal.beginGroup("init-%s" % client.name, "initialize client")

	# Very important caveat: We need to start rpcbind before enabling NIS.
	# Otherwise, rpcbind will hang on startup (NIS domain already set,
	# so getaddrinfo(3) will try to do a NIS query, and thus tries to ask
	# rpcbind to resolve service names such as rpcbind. Bleah.
	journal.beginTest("start rpcbind")
	if not client.runOrFail("systemctl enable rpcbind.socket") or \
	   not client.runOrFail("systemctl start rpcbind.socket"):
		return False

	journal.beginTest("Preparing configuration")

	journal.info("Set NIS domain to %s (/etc/defaultdomain)" % nisdomain)
	if not client.sendbuffer("/etc/defaultdomain", nisdomain):
		return False

	journal.info("set the NIS domain to %s (nisdomainname)" % nisdomain)
	if not client.runOrFail("nisdomainname '%s'" % nisdomain):
		return False

	journal.info("Add hostnames of master to /etc/hosts")
	client.addHostEntry(server.ipaddr, nismaster)
	if (server.ipv6_addr):
		client.addHostEntry(server.ipv6_addr, nismaster)

	client.nisBound = False
	journal.finishGroup()

##################################################################
# Stop ypbind
##################################################################
def nis_stop_client(client):
	global journal

	journal.beginGroup("stop-%s" % client.name, "stop client")

	journal.beginTest("stoping ypbind")
	if not client.runOrFail("rcypbind stop"):
		return False

	journal.beginTest("stop rpcbind")
	if not client.runOrFail("systemctl disable rpcbind.socket") or \
	   not client.runOrFail("systemctl stop rpcbind.socket"):
		return False

	journal.beginTest("Removing configuration")

	journal.info("Remove NIS domain")
	if not client.sendbuffer("/etc/defaultdomain", ""):
		return False

	journal.finishGroup()

##################################################################
# Test various ways to configure ypbind
##################################################################
def nis_test_binding(client,server):

	global nisdomain

	journal.beginGroup("ypbind", "Test different ypbind configuration modes")

	list = []
	list.append("domain %s broadcast" % nisdomain)
	list.append("broadcast")
	list.append("domain %s server %s" % (nisdomain, server.ipaddr))
	list.append("ypserver %s" % server.ipaddr)
	if server.ipv6_addr:
		list.append("domain %s server %s" % (nisdomain, nismaster))
		list.append("ypserver %s" % nismaster)
		list.append("domain %s server %s" % (nisdomain, server.ipv6_addr))
		list.append("ypserver %s" % server.ipv6_addr)

	for ypconf in list:
		journal.beginTest("validate binding when using \"%s\"" % ypconf)
		nis_configure_binding(client, ypconf)
		# Not more then 5 restarts in 10 seconds, else systemd will go crazy :(
		time.sleep (2)

	# TBD: use "ypwhich -m rpc" and verify that the name of the master
	# returned is nismaster.testing.suse.de

	client.runOrFail("rcypbind stop")
	client.nisBound = False
	journal.finishGroup()

def nis_ensure_bound(client,server):

	if client.nisBound:
		return True

	journal.beginTest("binding client to NIS server")
	if (server.ipv6_addr):
		ypconf = "domain %s server %s" % (nisdomain, nismaster)
	else:
		ypconf = "domain %s server %s" % (nisdomain, server.ipv4_addr)
	nis_configure_binding(client, ypconf)

	return client.nisBound

##################################################################
# Update yp.conf and rebind
##################################################################
def nis_configure_binding(client, ypconf):

	journal.info("Updating yp.conf")
	if not client.sendbuffer("/etc/yp.conf", ypconf):
		return False

	journal.info("Restart ypbind")
	client.nisBound = False
	if not client.runOrFail("rcypbind restart"):
		return False

	journal.info("Verify client binding")
	bound = None
	for i in range(1, 120/5):
		st = client.run("ypwhich -d %s" % nisdomain)
		if not st:
			journal.failure("ypwhich failed")
			return False

		bound = str(st.stdout);
		if bound:
			break

		time.sleep(5)

	if not bound:
		journal.failure("failed to bind to server")
		return False

	# It would be nice to verify whether we've bound to the
	# expected server or not. However, ypwhich returns the
	# hostname rather than the address.
	# We could use "getent -s files host <ipaddr>" to
	# map the address to the hostname, and match those,
	# but this looks like a lot of work for minimal gain.
	# After all, there should be only one such server on the
	# network in this test environment.
	journal.success("Successfully bound to %s" % bound)
	client.nisBound = True
	return True

def nis_switch_client_to_localhost(client, server):
	global nisdomain

	journal.beginGroup("localhost-%s" % client.name, "change yp.conf to localhost on %s" % client.name)

	if server.ipv6_addr:
		ypconf = "domain %s server localhost" % (nisdomain)
	else:
		ypconf = "domain %s server 127.0.0.1" % (nisdomain)

	nis_configure_binding(client, ypconf)

	journal.finishGroup()


##################################################################
# Enable passwd and group compat lookups
##################################################################
def nis_enable_compat_lookups(client, mapname):

	global journal

	filename = "/etc/" + mapname

	if not nsswitch_set_method(client, mapname, "compat"):
		return False

	journal.beginTest("add + entry to %s" % filename)
	if not client.run("test -f %s.twpsave" % filename):
		client.run("cp -av %s %s.twpsave" % (filename, filename))
	data = client.recvbuffer(filename)
	if not data:
		return False

	result = []
	for line in str(data).strip().split('\n'):
		if line[0] == '+':
			# In theory, this could be a +kukuk, but that's not the default
			# we ship :-)
			journal.success("%s already contains a line starting with +" % filename);
			return True
		result.append(line)

	result.append("+")

	data = '\n'.join(result) + '\n'
	return client.sendbuffer(filename, data);

##################################################################
# Disable passwd and group compat lookups
##################################################################
def nis_disable_compat_lookups(client, mapname):

	global journal

	filename = "/etc/" + mapname

	journal.beginTest("Restore backup of %s" % filename)
	if client.run("test -f %s.twpsave" % filename):
		client.run("mv %s.twpsave %s" % (filename, filename))

	return True

##################################################################
# Enable password updates through NIS
##################################################################
def nis_pam_unix_enable(client, filename):

	global journal

	journal.beginTest("enable NIS for PAM password updates")
	data = client.recvbuffer(filename)
	if not data:
		return False

	result = []
	for line in str(data).strip().split('\n'):
		words = line.split()
		if len(words) > 2 and words[0] == "password" and words[2] == "pam_unix.so":
			if not "nis" in words:
				line += " nis"
		result.append(line)

	data = '\n'.join(result) + '\n'
	return client.sendbuffer(filename, data);

##################################################################
# Change the lookup methods for a nsswitch map
##################################################################
def nsswitch_set_method(node, mapname, methods):

	global journal

	journal.beginTest("%s: configure nsswitch %s lookups for \"%s\"" % \
					(node.name, mapname, methods))

	# Save the original state of nsswitch.conf
	journal.info("Creating backup of nsswitch.conf if needed")
	if not client.run("test -f /etc/nsswitch.conf.twpsave"):
		client.run("cp -p /etc/nsswitch.conf /etc/nsswitch.conf.twpsave")

	data = node.recvbuffer("/etc/nsswitch.conf")
	if not data:
		journal.error("cannot download nsswitch.conf")
		return False

	result = []
	for line in str(data).strip().split('\n'):
		words = line.split(":")
		if words[0] == mapname:
			line = "%s: %s" % (mapname, methods)
		result.append(line)

	data = '\n'.join(result) + '\n'
	if not client.sendbuffer("/etc/nsswitch.conf", data):
		journal.error("cannot upload nsswitch.conf")
		return False

	journal.info("Reloading nscd configuration")
	client.run("rcnscd restart")

	return True

##################################################################
# Restore the lookup methods of nsswitch for all services
##################################################################
def restore_nsswitch(node):

	global journal

	journal.beginTest("%s: restore nsswitch" % (node.name))

	# Save the original state of nsswitch.conf
	journal.info("Restore backup of nsswitch.conf if needed")
	if client.run("test -f /etc/nsswitch.conf.twpsave"):
		client.run("mv /etc/nsswitch.conf.twpsave /etc/nsswitch.conf")

	journal.info("Reloading nscd configuration")
	client.run("rcnscd restart")

	return True

def nis_build_maps(mapname):

	global journal, nisdomain

	journal.beginTest("rebuild NIS map %s on the server" % mapname)
	server.run("make -C /var/yp/%s -f /var/yp/Makefile %s" % (nisdomain, mapname))

	journal.info("invalidate cached %s information on the client" % mapname)
	client.run("nscd -i %s" % mapname)

def nis_verify_map_notempty(mapname):

	global journal, client

	journal.beginTest("Make sure ypcat %s works" % mapname)
	st = client.runOrFail("ypcat %s" % mapname, quiet = True)
	if not st:
		return False

	if not st.stdout:
		journal.failure("ypcat returned an empty map")
		return False

	journal.success("ypcat returned map data (%u lines)" % len(str(st.stdout).split('\n')))
	return True

def nis_verify_ypmatch(mapname, key, value):
	global journal, client

	journal.beginTest("verify ypmatch %s %s (expect %s)" % (key, mapname, value))
	st = client.run("ypmatch %s %s" % (key, mapname))
	if not st:
		if value:
			journal.failure("ypmatch reported an error (should have succeeded)")
			return False
		journal.success("ypmatch reported an error, as it should")
		return True

	if not st.stdout:
		journal.failure("ypmatch returned an empty string")
		return False

	if value == "notempty":
		journal.success("ypmatch returned a non-empty string")
		return True

	if not (value in str(st.stdout)):
		journal.failure("ypmatch output did not contain %s" % value)
		return False

	journal.success()
	return True


##################################################################
# Test NIS host lookups
##################################################################
def nis_test_host_lookups(hostname, address):
	global journal, client, server

	journal.beginGroup("hosts", "Validate host lookup functionality")

	nis_ensure_bound(client,server)

	# Add a special host entry to the server's hosts file
	journal.beginTest("Add %s to the server hosts file" % hostname)
	server.addHostEntry(address, hostname)

	# Now rebuild the hosts maps
	nis_build_maps("hosts")

	nis_verify_map_notempty("hosts.byname")
	nis_verify_map_notempty("hosts.byaddr")
	nis_verify_map_notempty("hosts")

	nis_verify_ypmatch("hosts.byname", hostname, address)
	nis_verify_ypmatch("hosts.byaddr", address, hostname)

	journal.beginTest("enable NIS hosts lookups in NSS")
	if not nsswitch_set_method(client, "hosts", "files nis"):
		return False

	verify_hosts_byname(client, hostname, address)
	verify_hosts_byaddr(client, address, hostname)

	restore_nsswitch(client)
	journal.finishGroup()

def verify_hosts_byname(client, hostname, expected_addr):

	journal.beginTest("Verify host lookup of %s" % hostname)
	st = client.runOrFail("getent hosts %s" % hostname)
	if not st:
		journal.failure("getent failed")
		return False

	result = str(st.stdout).strip().split('\n')
	if not result:
		journal.failure("getent didn't return anything")
		return False

	for line in result:
		words = line.split()
		if words[0] == expected_addr:
			journal.success()
			return True

	journal.failure("getent didn't return the expected address %s" % expected_addr)
	return False

def verify_hosts_byaddr(client, address, expected_hostname):

	journal.beginTest("Verify host lookup of %s" % address)
	st = client.runOrFail("getent hosts %s" % address)
	if not st:
		journal.failure("getent failed")
		return False

	result = str(st.stdout).strip().split('\n')
	if not result:
		journal.failure("getent didn't return anything")
		return False

	for line in result:
		names = line.split()[1:]
		if expected_hostname in names:
			journal.success()
			return True

	journal.failure("getent didn't return the expected hostname %s" % expected_hostname)
	return False

##################################################################
# Test NIS user lookups
##################################################################
def nis_test_user_lookups(username, uid, password):
	global journal, client, server

	journal.beginGroup("users", "Validate user lookup functionality")

	nis_ensure_bound(client,server)

	# Add a special user entry to the server's passwd file
	journal.beginTest("Add %s to the server passwd file" % username)
	journal.info("Remove user entry from previous run (if needed)")
	if server.run("grep -qs ^%s: /etc/passwd" % username):
		if not server.run("userdel %s" % username):
			journal.failure("Unable to remove existing user %s on server" % username)

	status = server.run("mkpasswd -m sha-256 \"%s\"" % password)
	hashpass = str(status.stdout).strip()
	if not server.run("useradd -M --password '%s' --uid %s %s" % (hashpass, uid, username)):
		journal.error("unable to create user %s" % username)
		return False

	# Now rebuild the passwd maps
	nis_build_maps("passwd")
	nis_build_maps("group")

	nis_verify_map_notempty("passwd.byname")
	nis_verify_map_notempty("passwd.byuid")
	nis_verify_map_notempty("passwd")
	nis_verify_map_notempty("group.byname")
	nis_verify_map_notempty("group.bygid")
	nis_verify_map_notempty("group")

	nis_verify_ypmatch("passwd.byname", username, username + ":")
	nis_verify_ypmatch("passwd.byuid", uid, username + ":")

	nis_enable_compat_lookups(client, "passwd")
	nis_enable_compat_lookups(client, "group")

	verify_user_byname(client, username, uid)
	verify_user_byuid(client, uid, username)

	nis_pam_unix_enable(client, "/etc/pam.d/common-password")

	client.run("ypcat passwd")

	# Test that PAM authenticate works
	verify_user_auth(client, username, password)

	# Test that PAM chauthtok works
	newpass = "S0eL1te="
	if verify_user_passwd(client, username, password, newpass):
		time.sleep(2)
		client.run("nscd -i passwd")
		verify_user_auth(client, username, newpass, " using the new password")

	journal.beginTest("delete user on server and rebuild maps")
	server.run("userdel %s" % username)
	nis_build_maps("passwd")
	nis_build_maps("group")

	nis_verify_ypmatch("passwd.byname", username, None)
	nis_verify_ypmatch("passwd.byuid", uid, None)
	nis_disable_compat_lookups(client, "passwd")
	nis_disable_compat_lookups(client, "group")

	restore_nsswitch(client)
	journal.finishGroup()

def verify_user_byname(client, username, expected_uid):

	journal.beginTest("Verify lookup of user %s" % username)
	st = client.runOrFail("getent passwd %s" % username)
	if not st:
		journal.failure("getent failed")
		return False

	result = str(st.stdout).strip().split('\n')
	if not result:
		journal.failure("getent didn't return anything")
		return False

	expected_uid = str(expected_uid)
	for line in result:
		words = line.split(':')
		if len(words) >= 3 and words[2] == expected_uid:
			journal.success()
			return True

	journal.failure("getent didn't return the expected uid %s" % expected_uid)
	return False

def verify_user_byuid(client, uid, expected_username):

	journal.beginTest("Verify lookup of uid %s" % uid)
	st = client.runOrFail("getent passwd %s" % uid)
	if not st:
		journal.failure("getent failed")
		return False

	result = str(st.stdout).strip().split('\n')
	if not result:
		journal.failure("getent didn't return anything")
		return False

	for line in result:
		words = line.split(':')
		if words[0] == expected_username:
			journal.success()
			return True

	journal.failure("getent didn't return the expected username %s" % expected_username)
	return False

def verify_user_auth(client, username, password, how = ""):
	journal.beginTest("Try to authenticate as user %s%s" % (username, how))

	command = "pam-test --debug --pam-service login --username %s --password \"%s\" authenticate" % (username, password)
	return client.runOrFail(command)

def verify_user_passwd(client, username, oldpass, newpass):
	journal.beginTest("Try to change password for user %s" % username)

	command = "pam-test --debug --pam-service passwd --username %s --old-password \"%s\" --new-password \"%s\" chauthtok" % (username, oldpass, newpass)
	return client.runOrFail(command)

##################################################################
# Collection of regression tests
##################################################################
def nis_test_regressions():
	journal.beginGroup("regressions", "Collection of regression tests")
	nis_test_rpcbind_restart()
	yppoll_and_domain_not_bound()
	journal.finishGroup()

def nis_test_rpcbind_restart():

	journal.beginTest("Ensure that rpcbind does not hang in hostname lookups")
	journal.info("Restarting rpcbind - if this times out, rpcbind gets stuck in NIS calls (which it should avoid)")
	if not client.runOrFail("systemctl restart rpcbind.service", timeout = 30):
		return False

	journal.success()
	return True

def yppoll_and_domain_not_bound():
	journal.beginTest("Ensure that yppoll does not crash if domain is not bound")
	journal.info("Configure ypbind to invalid host/domain")

	client.nisBound = False;
	if not client.sendbuffer("/etc/yp.conf", "domain none-ignore server 127.0.0.1"):
		return False

	journal.info("Restart ypbind")
	if not client.runOrFail("rcypbind restart"):
		return False

	st = client.run("yppoll passwd.byname", quiet=True)
	if (st.code > 256):
		journal.failure("yppoll crashed: %s" % st.code)
		return False

	journal.success()
	return True


##################################################################
#
##################################################################
def main():
	setup()
	nis_init_master_server(server);
	nis_init_client(client, server);
	nis_test_binding(client, server)
	nis_test_host_lookups("teletubby.testing.suse.org", "8.8.8.8")
	# nis_test_host_lookups("teletubby6.testing.suse.org", "::2")
	nis_test_user_lookups("nistest", 6666, "MyPassword")
	nis_test_regressions()

	nis_init_slave_server(client)
	nis_switch_client_to_localhost(client, server)

	nis_stop_client(client)
	nis_stop_slave_server(client)
	nis_stop_master_server(server)

	journal.writeReport()

try:
        main()
except:
        import traceback

        journal.error("Oops, caught unexpected exception")
        journal.info(traceback.format_exc(None))

journal.writeReport()
if (journal.num_failed() + journal.num_errors()):
        sys.exit(1)
sys.exit(0)
